title = "Woody Dialogue Test"
background = "media/woodydialoguetest/WoodyDialogueTest.png"

[head]

[[head.element]]
credits = "Created by Rendew. Woody &copy Disney/Pixar."

[body]

[[body.element]]
tag = "hr"

[[body.element]]
date = "Lip-sync animation test with Woody. January 3 - ???, 2023"

[[body.element]]
tag = "img"
src = "media/woodydialoguetest/WoodyDialogueTest.png"

[[body.element]]
tag = "h2"
content = "Overview"

[[body.element]]
video = ["media/woodydialoguetest/blast3DmfHE.mov", "media/WoodyTestAnimationFinal.mp4"]
caption = "Frames: ???. FPS: 24. Working time: ??? hrs. Maya Viewport Playblast."
loop = true

[[body.element]]
video = ["media/woodydialoguetest/WoodyDialogueTestSound2.mov", "media/WoodyTestAnimationFinal.mp4"]
caption = "Frames: ???. FPS: 24. Working time: ??? hrs. Rendered with Renderman."
loop = true

[[body.element]]
tag = "h4"
content = "Coming soon!"